inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'spec/fixtures/**/*'
  TargetRubyVersion: 2.3

Layout/EndOfLine:
  EnforcedStyle: lf

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'
