user: ~
password: ~
generators:
  - RubyBuiltin
  - CxxBuiltin
ext_settings:
  'awk':
    submit_lang: '4009' # Awk (mawk)
  'bf':
    submit_lang: '4062' # Brainfuck
  'c':
    submit_lang: '4001' # C (GCC)
    test_cmd:
      default: '"{dir}/{base}"'
      windows: '"{dir}/{base}.exe"'
  'cbl':
    submit_lang: '4061' # COBOL - Free
  'clj':
    submit_lang: '4013' # Clojure
  'cr':
    submit_lang: '4014' # Crystal
  'cs':
    submit_lang: '4011' # C# (Mono-mcs)
    test_cmd:
      default: 'mono "{dir}/{base}.exe"'
      windows: '"{dir}/{base}.exe"'
  'cxx':
    submit_lang: '4003' # C++ (GCC)
    test_cmd:
      default: '"{dir}/{base}"'
      windows: '"{dir}/{base}.exe"'
  'd':
    submit_lang: '4015' # D (DMD64)
  'dart':
    submit_lang: '4018' # Dart
  'f90':
    submit_lang: '4025' # Fortran (gfortran)
  'fs':
    submit_lang: '4023' # F# (Mono)
  'go':
    submit_lang: '4026' # Go
  'hs':
    submit_lang: '4027' # Haskell (GHC)
  'java':
    submit_lang: '4005' # Java (OpenJDK)
    test_cmd:
      default: 'java -cp "{dir}" Main'
  'jl':
    submit_lang: '4031' # Julia
  'js':
    submit_lang: '4030' # JavaScript (node.js)
  'kt':
    submit_lang: '4032' # Kotlin
  'lisp':
    submit_lang: '4038' # Common Lisp
  'lua':
    submit_lang: '4034' # LuaJIT
  'm':
    submit_lang: '4040' # Octave
  'ml':
    submit_lang: '4039' # OCaml
  'nim':
    submit_lang: '4036' # Nim
  'pas':
    submit_lang: '4041' # Pascal (FPC)
  'php':
    submit_lang: '4044' # PHP7
  'pl':
    submit_lang: '4042' # Perl
  'py':
    submit_lang: '4006' # Python3
  'rb':
    submit_lang: '4049' # Ruby
    test_cmd:
      default: 'ruby "{dir}/{base}.rb"'
  'rs':
    submit_lang: '4050' # Rust
  'scala':
    submit_lang: '4051' # Scala
  'scm':
    submit_lang: '4053' # Scheme (Gauche)
  'sed':
    submit_lang: '4066' # Sed (GNU sed)
  'sh':
    submit_lang: '4007' # Bash (GNU bash)
  'swift':
    submit_lang: '4055' # Swift
  'ts':
    submit_lang: '4057' # TypeScript
  'txt':
    submit_lang: '4056' # Text (cat)
  'vb':
    submit_lang: '4058' # Visual Basic (Mono)
