user: ~
password: ~
generators:
  - RubyBuiltin
  - CxxBuiltin
ext_settings:
  'awk': # Awk (mawk)
    submit_lang:
      - '4009'
      - '3506'
  'bf': # Brainfuck
    submit_lang:
      - '4062'
      - '3507'
  'c': # C (GCC)
    submit_lang:
      - '4001'
      - '3002'
    test_cmd:
      default: '"{dir}/{base}"'
      windows: '"{dir}/{base}.exe"'
  'cbl': # COBOL - Free
    submit_lang:
      - '4061'
      - '3526'
  'clj': # Clojure
    submit_lang:
      - '4013'
      - '3007'
  'cr': # Crystal
    submit_lang:
      - '4014'
      - '3511'
  'cs': # C# (Mono-mcs)
    submit_lang:
      - '4011'
      - '3006'
    test_cmd:
      default: 'mono "{dir}/{base}.exe"'
      windows: '"{dir}/{base}.exe"'
  'cxx': # C++ (GCC)
    submit_lang:
      - '4003'
      - '3003'
    test_cmd:
      default: '"{dir}/{base}"'
      windows: '"{dir}/{base}.exe"'
  'd': # D (DMD64)
    submit_lang:
      - '4015'
      - '3009'
  'dart': # Dart
    submit_lang: '4018'
  'f90': # Fortran (gfortran)
    submit_lang:
      - '4025'
      - '3012'
  'fs': # F# (Mono)
    submit_lang:
      - '4023'
      - '3512'
  'go': # Go
    submit_lang:
      - '4026'
      - '3013'
  'hs': # Haskell (GHC)
    submit_lang:
      - '4027'
      - '3014'
  'java': # Java (OpenJDK)
    submit_lang:
      - '4005'
      - '3016'
    test_cmd:
      default: 'java -cp "{dir}" Main'
  'jl': # Julia
    submit_lang:
      - '4031'
      - '3518'
  'js': # JavaScript (node.js)
    submit_lang:
      - '4030'
      - '3017'
  'kt': # Kotlin
    submit_lang:
      - '4032'
      - '3523'
  'lisp': # Common Lisp
    submit_lang:
      - '4038'
      - '3008'
  'lua': # LuaJIT
    submit_lang:
      - '4034'
      - '3515'
  'm': # Octave
    submit_lang:
      - '4040'
      - '3519'
  'ml': # OCaml
    submit_lang:
      - '4039'
      - '3018'
  'nim': # Nim
    submit_lang:
      - '4036'
      - '3520'
  'pas': # Pascal (FPC)
    submit_lang:
      - '4041'
      - '3019'
  'php': # PHP7
    submit_lang:
      - '4044'
      - '3524'
  'pl': # Perl
    submit_lang:
      - '4042'
      - '3020'
  'py': # Python3
    submit_lang:
      - '4006'
      - '3023'
  'rb': # Ruby
    submit_lang:
      - '4049'
      - '3024'
    test_cmd:
      default: 'ruby "{dir}/{base}.rb"'
  'rs': # Rust
    submit_lang:
      - '4050'
      - '3504'
  'scala': # Scala
    submit_lang:
      - '4051'
      - '3025'
  'scm': # Scheme (Gauche)
    submit_lang:
      - '4053'
      - '3026'
  'sed': # Sed (GNU sed)
    submit_lang:
      - '4066'
      - '3505'
  'sh': # Bash (GNU bash)
    submit_lang:
      - '4007'
      - '3001'
  'swift': # Swift
    submit_lang:
      - '4055'
      - '3503'
  'ts': # TypeScript
    submit_lang:
      - '4057'
      - '3521'
  'txt': # Text (cat)
    submit_lang:
      - '4056'
      - '3027'
  'vb': # Visual Basic (Mono)
    submit_lang:
      - '4058'
      - '3028'
